### PR TITLE
Fixes For Nobara Linux

### PR DESCRIPTION
**Pull request by user1126s**
# the main scripts are copied and edited in folder nobara-linux and a section in readme is added that tells how to install on nobara linux 39

#24 
# Some fixes for nobara linux

## changes that allow installation on nobara linux.
 
changed so it executes nobara-sync (nobara-system-upgrader) instead of dnf update because dnf-update replaces lots of multimedia codecs which require a reinstall from nobara-updater. 

changed to include dnf4 in commands like dnf copr and dnf list. dnf list has issues and dnf copr doesnt exist in dnf5.

# more testing needed.

## Type of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/JaKooLit/Fedora-Hyprland/blob/main/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My commit message follows the [commit guidelines](https://github.com/JaKooLit/Fedora-Hyprland/blob/main/CONTRIBUTING.md#git-commit-messages).

### CODE REVIEW

**Comment by user1126s** [comment]
testing on my main pc rn

**Comment by user1126s** [comment]
# nobara system upgrader also uses dnf5, but works and still is fast.

**Comment by user1126s** [comment]
GG It works 
Screenshot_24-Jan_14-52-15_kitty

**Comment by JaKooLit** [comment]
kindly merge it to development

**Comment by user1126s** [comment]
will i lose anything

**Comment by user1126s** [comment]
alright

**Pull request closed without merging**
